name: Deploy to CloudFlare

on:
  workflow_dispatch:
  push:
    branches: ["upstream"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'upstream'
      - run: wget https://raw.githubusercontent.com/boris1993/gh-proxy/refs/heads/master/wrangler.toml
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
