name: Deploy to CloudFlare

on:
  workflow_dispatch:
  push:
    branches: ["upstream"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      # Check out the code
      - uses: actions/checkout@v4
        with:
          ref: 'upstream'
          path: upstream
      # Check out the master branch for wrangler.toml
      - uses: actions/checkout@v4
        with:
          ref: 'master'
      - run: ls
      # - name: Publish
      #   uses: cloudflare/wrangler-action@v3
      #   with:
      #     apiToken: ${{ secrets.CF_API_TOKEN }}
